name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  # push: {branches: ["master", "main"]}


jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: gh-metrics/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.COMMITTER_TOKEN }}
          plugin_achievements: yes
          user: guifelix
          filename: assets/svg/achievements.svg
          base: ""
          plugin_achievements_secrets: yes
          plugin_achievements_limit: 0
          committer_message: "📊 update metrics"
          template: classic
